### PR TITLE
removed words with spaces

### PR DESCRIPTION
**Pull request by kiraacorsac**
There are words with spaces in the lists. As it should be a word list, not a phrase list, I think it's fair to get rid of words that contain spaces.

### CODE REVIEW

**Comment by mrmaxguns** [comment]
I disagree. They're known as [open compounds](https://en.wiktionary.org/wiki/open_compound) and are still considered words. We might consider creating a filter for these words, but a space alone shouldn't warrant their removal from word lists.

**Comment by kiraacorsac** [comment]
Huh, did not know that. I understand that they should be kept. A filter makes sense, however - I think a lot of use-cases rely on words being just a single-stem or closed compounds.

**Comment by mrmaxguns** [comment]
That is true, but the goal of this library is to generate random words. The more restrictions imposed, the smaller the word list, and the less existing words will be chosen. For example, `dump truck` is a well-known word—it isn't an exception. I propose a `single_word` parameter (maybe set to `True` by default, thus avoiding the need to delete words) which will filter out words with spaces. Thank you for your concern and contribution!

**Comment by mrmaxguns** [comment]
Again, thanks for the feedback. I'll close this PR and will implement the word length filter. It will be shipped with Wonderwords V2.3 that's coming soon.

**Pull request closed without merging**
